/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin.dashboard'
import { Route as AuthenticatedAdminFeesRouteImport } from './routes/_authenticated/admin.fees'
import { Route as AuthenticatedAdminStudentsRouteImport } from './routes/_authenticated/admin.students'
import { Route as AuthenticatedSuperAdminDashboardRouteImport } from './routes/_authenticated/super-admin.dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFeesRoute = AuthenticatedAdminFeesRouteImport.update({
  id: '/admin/fees',
  path: '/admin/fees',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminStudentsRoute =
  AuthenticatedAdminStudentsRouteImport.update({
    id: '/admin/students',
    path: '/admin/students',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuperAdminDashboardRoute =
  AuthenticatedSuperAdminDashboardRouteImport.update({
    id: '/super-admin/dashboard',
    path: '/super-admin/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof AuthenticatedHomeRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/fees': typeof AuthenticatedAdminFeesRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/super-admin/dashboard': typeof AuthenticatedSuperAdminDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof AuthenticatedHomeRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/fees': typeof AuthenticatedAdminFeesRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/super-admin/dashboard': typeof AuthenticatedSuperAdminDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/fees': typeof AuthenticatedAdminFeesRoute
  '/_authenticated/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/_authenticated/super-admin/dashboard': typeof AuthenticatedSuperAdminDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/home'
    | '/admin/dashboard'
    | '/admin/fees'
    | '/admin/students'
    | '/super-admin/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/home'
    | '/admin/dashboard'
    | '/admin/fees'
    | '/admin/students'
    | '/super-admin/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/home'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/fees'
    | '/_authenticated/admin/students'
    | '/_authenticated/super-admin/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/fees': {
      id: '/_authenticated/admin/fees'
      path: '/admin/fees'
      fullPath: '/admin/fees'
      preLoaderRoute: typeof AuthenticatedAdminFeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/students': {
      id: '/_authenticated/admin/students'
      path: '/admin/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AuthenticatedAdminStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/super-admin/dashboard': {
      id: '/_authenticated/super-admin/dashboard'
      path: '/super-admin/dashboard'
      fullPath: '/super-admin/dashboard'
      preLoaderRoute: typeof AuthenticatedSuperAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminFeesRoute: typeof AuthenticatedAdminFeesRoute
  AuthenticatedAdminStudentsRoute: typeof AuthenticatedAdminStudentsRoute
  AuthenticatedSuperAdminDashboardRoute: typeof AuthenticatedSuperAdminDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminFeesRoute: AuthenticatedAdminFeesRoute,
  AuthenticatedAdminStudentsRoute: AuthenticatedAdminStudentsRoute,
  AuthenticatedSuperAdminDashboardRoute: AuthenticatedSuperAdminDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
